JB/urls.py
from django.contrib import admin
from django.urls import path,include
import birthday.urls
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(birthday.urls)),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

birthday/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('home/',views.home,name="home"),
    path('memories/',views.memories,name="memories"),
    path('videos/',views.videos,name="videos"),
    path('stories/',views.stories,name="stories"),
    path('addmemories/',views.addmemories,name="addmemories"),
    path('addvideos/',views.addvideos,name="addvideos"),
    path('addstories/',views.addstories,name="addstories"),
    path('about/',views.about,name="about"),
    path('logout/',views.logout,name="logout"),
    path('DeleteVideo/<int:v_id>/',views.DeleteVideo,name="DeleteVideo"),
    path('DeleteMemory/<int:m_id>/',views.DeleteMemory,name="DeleteMemory"),
    path('DeleteStory/<int:s_id>/',views.DeleteStory,name="DeleteStory"),


]

birthday/models.py
from django.db import models
from django.urls import reverse


class Memories(models.Model):
    title=models.CharField(max_length=100,default=None,null=True,verbose_name="Title")
    image=models.FileField(upload_to="images/")

    def __str__(self):
        return self.title
    
    

class Jayanth(models.Model):
    email=models.CharField(max_length=50,primary_key=True,default=None,verbose_name="Email")
    password=models.CharField(max_length=50,default=None,verbose_name="Password")

class Stories(models.Model):
    title=models.CharField(max_length=100,default=None,null=True,verbose_name="Title")
    Story=models.CharField(max_length=10000,default=None,null=True,verbose_name="Content")

    def __str__(self):
        return self.title


class Videos(models.Model):
    title=models.CharField(max_length=100,default=None,null=True,verbose_name="Title")
    video=models.FileField(upload_to="videos/")
    
    def __str__(self):
        return self.title

    
    
    
    

birthday/forms.py
from django import forms
from . import models

class MemoriesForm(forms.Form):
    title=forms.CharField()
    image=forms.FileField()

class VideosForm(forms.Form):
    title=forms.CharField()
    video=forms.FileField()

class StoriesForm(forms.Form):
    title=forms.CharField()
    Story=forms.CharField()

class UserForm(forms.Form):
    email=forms.CharField()
    password=forms.CharField()

birthday/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse,reverse_lazy
from . forms import MemoriesForm,VideosForm,StoriesForm,UserForm
from django.views.generic import DeleteView
from . models import Memories,Videos,Stories,Jayanth
import os


def memories(request):
    memor=Memories.objects.all()
    current_user=request.session.get('user_ses',None)
    return render(request,'birthday/memories.html',{'memor':memor,'current_user':current_user})    

def videos(request):
    memor=Videos.objects.all()
    current_user=request.session.get('user_ses',None)
    return render(request,'birthday/videos.html',{'memor':memor,'current_user':current_user})

def stories(request):
    memor=Stories.objects.all()
    current_user=request.session.get('user_ses',None)
    return render(request,'birthday/stories.html',{'memor':memor,'current_user':current_user})

def about(request):
    current_user=request.session.get('user_ses',None)
    return render(request,'birthday/about.html',{'current_user':current_user})

def home(request):
    if request.method=='POST':
        form=UserForm(request.POST)
        if form.is_valid():
            e=form.cleaned_data['email']
            p=form.cleaned_data['password']
            yes=Jayanth.objects.filter(email=e)
            if yes.exists():
                request.session['user_ses']=e
                current_user=request.session['user_ses']
                return render(request,'birthday/index.html',{'current_user':current_user})
            else:
                err="User Doesn't exist"
                return render(request,'birthday/index.html',{'err':err,'form':form})
        else:
            err="Check Your Fields"
            return render(request,'birthday/index.html',{'err':err,'form':form})
    else:
        form=UserForm()
        current_user=request.session.get('user_ses',None)
    return render(request,'birthday/index.html',{'form':form,'current_user':current_user})

def addmemories(request):
    if request.session.get('user_ses',None):
        if request.method=='POST':
            form=MemoriesForm(request.POST,request.FILES)
            if form.is_valid():
                t=form.cleaned_data['title']
                i=form.cleaned_data['image']
                record=Memories(title=t,image=i)
                record.save()
                return HttpResponseRedirect(reverse('memories'))
            else:
                field_error="please check the fields"
                return render(request,'birthday/memories_form.html',{'form':form,'field_error':field_error})
        else:
            form=MemoriesForm()
        return render(request,'birthday/memories_form.html',{'form':form})
    else:
        return  HttpResponseRedirect(reverse('memories'))

def addvideos(request):
    if request.session.get('user_ses',None):
        if request.method=='POST':
            form=VideosForm(request.POST,request.FILES)
            if form.is_valid():
                t=form.cleaned_data['title']
                i=form.cleaned_data['video']
                record=Videos(title=t,video=i)
                record.save()
                return HttpResponseRedirect(reverse('videos'))
            else:
                field_error="please check the fields"
                return render(request,'birthday/videoform.html',{'form':form,'field_error':field_error})
        else:
            form=MemoriesForm()
        return render(request,'birthday/videoform.html',{'form':form})
    else:
        return  HttpResponseRedirect(reverse('videos'))


def addstories(request):
    if request.session.get('user_ses',None):
        if request.method=='POST':
            form=StoriesForm(request.POST)
            if form.is_valid():
                t=form.cleaned_data['title']
                i=form.cleaned_data['Story']
                record=Stories(title=t,Story=i)
                record.save()
                return HttpResponseRedirect(reverse('stories'))
            else:
                field_error="please check the fields"
                return render(request,'birthday/storyform.html',{'form':form,'field_error':field_error})
        else:
            form=StoriesForm()
        return render(request,'birthday/storyform.html',{'form':form})
    else:
        return HttpResponseRedirect(reverse('stories'))


def DeleteStory(request,s_id):
    record=Stories.objects.filter(id=s_id)
    record.delete()
    return HttpResponseRedirect(reverse('stories'))
    

def DeleteMemory(request,m_id):
    record=Memories.objects.get(id=m_id)
    record.image.delete()
    record.delete()
    return HttpResponseRedirect(reverse('memories'))
    


def DeleteVideo(request,v_id):
    record=Videos.objects.get(id=v_id)
    record.video.delete()
    record.delete()
    return HttpResponseRedirect(reverse('videos'))
    
def logout(request):
    try:
        del request.session['user_ses']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse('home'))

birthday/templates/birthday/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Happy Birthday Jay!</title>
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'birthday/assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'birthday/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ml-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'memories' %}">Memories</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'videos' %}">Videos</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'stories' %}">Stories</a></li>
                        {% if current_user %}
                            <li class="nav-item"><a class="nav-link j-scroll-trigger" href="{% url 'logout' %}">Logout</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#portfolio">About</a></li>
                    </ul>
                </div>
            </div>
        </nav>
       
         

        <section class="page-section bg-light" id="portfolio">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Developed By</h2>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'birthday/assets/img/team/shivas.jpg' %}" alt="" />
                            <h4>Shiva Teja</h4>
                            <p class="text-muted">Student at HITAM</p>
                            <a class="btn btn-dark btn-social mx-2" href="https://github.com/ShivaTejaHitam?tab=repositories"><i class="fab fa-github"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/shivateja.bandaru/"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="https://www.linkedin.com/in/shiva-teja-10133a192/"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    
                </div>
                <div class="row">
                </div>
            </div>
        </section>

        
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-left"></div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        
                    </div>
                    <div class="col-lg-4 text-lg-right">
                        
                    </div>
                </div>
            </div>
        </footer>
        
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
        <script src="{% static 'birthday/assets/mail/jqBootstrapValidation.js' %}"></script>
        <script src="{% static 'birthday/assets/mail/contact_me.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'birthday/js/scripts.js' %}"></script>
    </body>
</html>

birthday/templates/birthday/memories_form.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Happy Birthday Jay!</title>
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'birthday/assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'birthday/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ml-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'memories' %}">Memories</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'videos' %}">Videos</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'stories' %}">Stories</a></li>
                        <li class="nav-item"><a class="nav-link j-scroll-trigger" href="{% url 'logout' %}">Logout</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'about' %}">About</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <!-- Contact-->
        <section class="page-section" id="contact">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Add New Photo</h2>
                </div>
                <form  name="sentMessage"  action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row align-items-stretch mb-5">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input class="form-control" id="id_title" name="title" type="text" placeholder="Enter Title *" required />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="form-group">
                                <input class="" id="id_image" name="image" type="file" accept="image/*" required/>
                                <p class="help-block text-danger"></p>
                            </div>   
                        </div>
                        
                    </div>
                   
                    <div class="text-center">
                        <div id="success"></div>
                        <input class="btn btn-primary btn-xl text-uppercase" value="Upload" type="submit">
                    </div>

                </form>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-left">Developed by Shiva Teja Bandaru</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-github"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-right">
                        <a class="mr-3" href="#!">Privacy Policy</a>
                        <a href="#!">Terms of Use</a>
                    </div>
                </div>
            </div>
        </footer>
        
        
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
        <script src="{% static 'birthday/assets/mail/jqBootstrapValidation.js' %}"></script>
        <script src="{% static 'birthday/assets/mail/contact_me.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'birthday/js/scripts.js' %}"></script>
    </body>
</html>

birthday/templates/birthday/storyform.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Happy Birthday Jay!</title>
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'birthday/assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'birthday/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ml-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'memories' %}">Memories</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'videos' %}">Videos</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'stories' %}">Stories</a></li>
                        <li class="nav-item"><a class="nav-link j-scroll-trigger" href="{% url 'logout' %}">Logout</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'about' %}">About</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <section class="page-section" id="contact">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Write New Story</h2>
                </div>
                <form  name="sentMessage"  action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row align-items-stretch mb-5">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input class="form-control" id="id_title" name="title" type="text" placeholder="Enter Title *" required />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="form-group form-group-textarea mb-md-0">
                                <textarea class="form-control" id="id_Story" name="Story" placeholder="Start Writing Here.." rows=100 required></textarea>
                                <p class="help-block text-danger"></p>
                            </div>   
                        </div>
                        
                    </div>
                   
                    <div class="text-center">
                        <div id="success"></div>
                        <input class="btn btn-primary btn-xl text-uppercase" value="Post" type="submit">
                    </div>

                </form>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-left">Developed by Shiva Teja Bandaru</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-github"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-right">
                        <a class="mr-3" href="#!">Privacy Policy</a>
                        <a href="#!">Terms of Use</a>
                    </div>
                </div>
            </div>
        </footer>
        
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
        <script src="{% static 'birthday/assets/mail/jqBootstrapValidation.js' %}"></script>
        <script src="{% static 'birthday/assets/mail/contact_me.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'birthday/js/scripts.js' %}"></script>
    </body>
</html>

birthday/templates/birthday/videoform.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content=""/>
        <meta name="author" content=""/>
        <title>Happy Birthday Jay!</title>
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'birthday/assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'birthday/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ml-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'memories' %}">Memories</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'videos' %}">Videos</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'stories' %}">Stories</a></li>
                        <li class="nav-item"><a class="nav-link j-scroll-trigger" href="{% url 'logout' %}">Logout</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'about' %}">About</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <section class="page-section" id="contact">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Add New Video</h2>
                </div>
                <form  name="sentMessage"  action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row align-items-stretch mb-5">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input class="form-control" id="id_title" name="title" type="text" placeholder="Enter Title *" required />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="form-group">
                                <input class="" id="id_video" name="video" type="file" accept="video/*" required/>
                                <p class="help-block text-danger"></p>
                            </div>   
                        </div>
                        
                    </div>
                   
                    <div class="text-center">
                        <div id="success"></div>
                        <input class="btn btn-primary btn-xl text-uppercase" value="Upload" type="submit">
                    </div>

                </form>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-left">Developed by Shiva Teja Bandaru</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-github"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-right">
                        <a class="mr-3" href="#!">Privacy Policy</a>
                        <a href="#!">Terms of Use</a>
                    </div>
                </div>
            </div>
        </footer>
        
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
        <script src="{% static 'birthday/assets/mail/jqBootstrapValidation.js' %}"></script>
        <script src="{% static 'birthday/assets/mail/contact_me.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'birthday/js/scripts.js' %}"></script>
    </body>
</html>